name: git tag

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  git-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0  # Fetch all history, needed for Nerdbank.GitVersioning
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine Git Version
        # ie: not on a pull request
        if: github.ref_name == 'main'
        uses: dotnet/nbgv@v0.4.2
        id: nbgv
      - name: Do Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          TAG=${{ steps.nbgv.outputs.SemVer2 }}
          git tag $TAG
          git push origin $TAG
